## Numpy Arrays

In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [6]:
myarray = np.array(mylist)

In [7]:
myarray

array([1, 2, 3])

In [8]:
type(myarray)

numpy.ndarray

In [9]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [16]:
np.arange(0, 101, 20)

array([  0,  20,  40,  60,  80, 100])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [23]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [25]:
np.linspace(0, 5, 21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [26]:
len(np.linspace(0, 5, 21))

21

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
np.random.rand(1)

array([0.85859348])

In [34]:
np.random.rand(2, 2)

array([[0.52930538, 0.59279325],
       [0.76024135, 0.49875916]])

In [35]:
np.random.rand(5, 2)

array([[0.09220847, 0.38381534],
       [0.79989273, 0.79476034],
       [0.82933044, 0.78168607],
       [0.73777135, 0.35752453],
       [0.25365543, 0.79097627]])

In [36]:
np.random.randn(10)

array([ 0.9347297 ,  0.90936868,  0.09603265, -0.07223719, -0.64575733,
        0.03920003,  1.49110002, -1.33910568, -1.10738306, -1.13038351])

In [37]:
np.random.randn(2, 3)

array([[-0.34443545,  0.16886865,  1.40551355],
       [-0.0490609 ,  0.34712606, -1.04287604]])

In [40]:
np.random.randint(0, 101, 5)

array([33, 43,  0, 24, 49])

In [41]:
np.random.randint(0, 101, (4, 5))

array([[43, 71, 95, 20, 54],
       [57, 18, 73, 19, 55],
       [30, 28, 39, 67, 28],
       [ 2, 77, 15, 12, 78]])

In [50]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [51]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [52]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [54]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [55]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [56]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [57]:
np.random.rand(4)

array([0.68527698, 0.83389686, 0.30696622, 0.89361308])

In [59]:
np.random.rand(4)

array([0.1818924 , 0.78560176, 0.96548322, 0.23235366])

In [60]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [61]:
array = np.arange(0, 25)

In [62]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [63]:
array.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [64]:
array.reshape(5, 4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [65]:
ranarr = np.random.randint(0, 101, 10)

In [66]:
ranarr

array([ 9, 77, 40,  4, 63, 40, 60, 92, 64,  5])

In [67]:
ranarr.max()

92

In [68]:
ranarr.min()

4

In [69]:
ranarr.argmax()

7

In [70]:
ranarr.argmin()

3

In [72]:
ranarr.dtype

dtype('int64')

In [74]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [75]:
array.shape

(25,)

In [76]:
array = array.reshape(5, 5)

In [77]:
array.shape

(5, 5)

In [78]:
array.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [79]:
array.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])