In [33]:
import numpy as np

In [34]:
arr = np.arange(0, 10)

In [35]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [38]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [40]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr / arr

/tmp/ipykernel_4455/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [44]:
1 / 0

ZeroDivisionError: division by zero

In [45]:
1 / arr

/tmp/ipykernel_4455/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [46]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [47]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [48]:
np.log(arr)

/tmp/ipykernel_4455/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [49]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr.sum()

45

In [51]:
arr.mean()

4.5

In [52]:
arr.max()

9

In [53]:
arr.min()

0

In [54]:
arr.var()

8.25

In [55]:
arr.std()

2.8722813232690143

In [56]:
np.arange(0, 25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
np.arange(0, 25).reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
arr2d = np.arange(0, 25).reshape(5, 5)

In [59]:
arr2d.shape

(5, 5)

In [60]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
arr2d.sum()

300

In [62]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [63]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])