In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df = pd.read_csv('../08-linear-regression-models/Advertising.csv')

In [11]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [12]:
X = df.drop('sales', axis=1)

In [13]:
y = df['sales']

In [14]:
from sklearn.preprocessing import PolynomialFeatures

In [15]:
polynomial_converter = PolynomialFeatures(degree=2, include_bias=False)

In [16]:
polynomial_converter.fit(X)

PolynomialFeatures(include_bias=False)

In [17]:
poly_features = polynomial_converter.transform(X)

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
poly_features.shape

(200, 9)

In [21]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [22]:
from sklearn.linear_model import LinearRegression

In [23]:
model = LinearRegression()

In [24]:
model.fit(X_train, y_train)

LinearRegression()

In [25]:
test_prediction = model.predict(X_test)

In [26]:
model.coef_

array([ 5.17095811e-02,  1.30848864e-02,  1.20000085e-02, -1.10892474e-04,
        1.14212673e-03, -5.24100082e-05,  3.34919737e-05,  1.46380310e-04,
       -3.04715806e-05])

In [27]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [28]:
MAE = mean_absolute_error(y_test, test_prediction)

In [29]:
MSE = mean_squared_error(y_test, test_prediction)

In [30]:
RMSE = np.sqrt(MSE)

In [31]:
MAE

0.48967980448037

In [32]:
RMSE

0.6646431757269196

In [33]:
model.coef_

array([ 5.17095811e-02,  1.30848864e-02,  1.20000085e-02, -1.10892474e-04,
        1.14212673e-03, -5.24100082e-05,  3.34919737e-05,  1.46380310e-04,
       -3.04715806e-05])

In [34]:
poly_features[0]

array([2.301000e+02, 3.780000e+01, 6.920000e+01, 5.294601e+04,
       8.697780e+03, 1.592292e+04, 1.428840e+03, 2.615760e+03,
       4.788640e+03])

In [35]:
X.iloc[0]

TV           230.1
radio         37.8
newspaper     69.2
Name: 0, dtype: float64

In [36]:
69.2 ** 2

4788.64